### ISSUE TITLE
[rss provider] Images break the layout

### ISSUE THREAD

**Issue by v0d** [j6k4m8/goosepaper#22]
Images referenced in RSS feeds are not scaled to match the column width and overlap with the other column, rendering the contend "not so good readable".

Example RSS feed used: https://vietnamnews.vn/rss/world.rss

See rendered PDF:
[Goosepaper.pdf](https://github.com/j6k4m8/goosepaper/files/5618450/Goosepaper.pdf)

**Comment by j6k4m8** [comment]
omg that's so bad, I'm sorry!  I'll look into this right away! perhaps @sterlingbaldwin may have encountered this issue as well?

**Comment by j6k4m8** [comment]
Just pushed a change, let me know if that fixes your problem and I'll close this issue :) tested it with your RSS feed and it appears to be solved but want to make sure it's working for you!

**Comment by v0d** [comment]
Yeeha - @j6k4m8 , this fixed the layout issue! (Trump is now not covering all columns anymore :) )

Thank you!

I really like this project and look forward to its development. I incorporate it now in my morning reading routine!

**Comment by j6k4m8** [comment]
He doesn't even deserve to have the ONE column, and CERTAINLY not two!!

I'm so glad it's helpful to you! Please let me know if you ever encounter any trouble, I love hearing about these success stories! :D
