### ISSUE TITLE
Error at upload stage

### ISSUE THREAD

**Issue by lapwat** [j6k4m8/goosepaper#24]
# Context

- I cloned this repo and did not make any modification to `example-config.json`
- I mount the file generated by `rmapi`, because `rmapy` and `rmapi` are using the same file format.

> If you previously used the go package rmapi ,the keys for authorization are re-used because we use the same storage location & format.
https://rmapy.readthedocs.io/en/latest/quickstart.html

Tell me if you need more context.

# Command

`docker run -it --rm -v $(pwd):/goosepaper/mount -v $HOME/.config/rmapi/rmapi.conf:/root/.rmapy j6k4m8/goosepaper goosepaper -c mount/example-config.json -o mount/Goosepaper.pdf --upload`

# Error

```sh
Traceback (most recent call last):
  File "/usr/local/bin/goosepaper", line 33, in <module>
    sys.exit(load_entry_point('goosepaper', 'console_scripts', 'goosepaper')())
  File "/goosepaper/goosepaper/__main__.py", line 63, in main
    upload(args.output)
  File "/goosepaper/goosepaper/upload.py", line 40, in upload
    if item.VissibleName == filepath.stem:
AttributeError: 'str' object has no attribute 'stem'
```

**Comment by j6k4m8** [comment]
Working on this now!!

**Comment by j6k4m8** [comment]
Frustratingly, [docker hub](https://hub.docker.com/r/j6k4m8/goosepaper/builds) doesn't show the failed builds. But looks like the image hasn't been updating with the last few pushes. Appears to be a bug on their end, although I hesitate to blame anyone other than myself :)

<img width="534" alt="image" src="https://user-images.githubusercontent.com/693511/100820804-06efb200-341d-11eb-861d-d350fb3f5eca.png">

This should be fixed on the latest `master` branch. I even pushed a new image to Docker Hub and it didn't accept it! Not sure what's going on. Hang tight, still playing around and I'll see if I can get you a fix in the next few minutes.

**Comment by j6k4m8** [comment]
*....aaaaAAAAAAND* we're back! Try now, @lapwat? (btw, just cloned your md2mobi repo, that looks super cool!)

**Comment by lapwat** [comment]
Honk! Upload successful!

**Comment by j6k4m8** [comment]
HONK HONK HONK HONK
