### ISSUE TITLE
Configurable font size

### ISSUE THREAD

**Issue by j6k4m8** [j6k4m8/goosepaper#25]
Users should be able to select body-text font size in rendered PDFs

**Comment by josephcscarpa** [comment]
I'm interested

**Comment by j6k4m8** [comment]
Awesome @josephcscarpa!! I think we'll add a new item to the json config called `font_size`, which is optional and default to something reasonable. (I think the current font-size is `14`). "Defaulting" can happen when we parse the config file, which happens [here](https://github.com/j6k4m8/goosepaper/blob/master/goosepaper/__main__.py#L48). Right now we just get a list of story providers; let's ALSO look inside `config` for that `font_size` key, and if it doesn't exist, we'll set it to 14 for now.

Once we have the user's preferred font-size, we'll need to pass that into the CSS that we use to draw the document. [Here](https://github.com/j6k4m8/goosepaper/blob/master/goosepaper/styles.py#L49) is where the current font-size is defined. So we'll need to change that to accept a variable: When we call `get_css` ([source](https://github.com/j6k4m8/goosepaper/blob/master/goosepaper/styles.py#L5)), we'll allow an optional variable called `font_size`, and then use python's [f-string syntax](https://realpython.com/python-formatted-output/#f-string-syntax) to interpolate the user's choice into the giant CSS string.

Okay — phew! That's a lot to chew on. In short, I think it looks like this:

- [ ] Add font size to config file
- [ ] Pass user's preference (or default) to the Style class
- [ ] Interpolate that variable into the CSS using an f-string

How does this sound? If you think it'd be helpful, happy to hang out on a zoom call and pair-program this together! :)

**Comment by j6k4m8** [comment]
By the way, if you want to start developing and take out a draft pull-request, we can also discuss there as you write :)

**Comment by josephcscarpa** [comment]
Hello! Sorry it has taken so long to get back to you. I have a couple of things coming up in the next few days. I'd want to take a look at the code base and familiarize myself with it as I haven't taken on any substantial Python project. If you solve this issue by then, I'll take a look for something else!

**Comment by josephcscarpa** [comment]
The instructions you gave make sense! Also, I am on Windows so that is part of why I am taking so long.

**Comment by j6k4m8** [comment]
No problem, I totally understand! Lots of stuff going on these days :)

To be perfectly honest, I haven't tried out Goosepaper on windows. I
suspect it works, but I'm not sure! In your experiences if you encounter
any bugs or good-to-knows, I think it'd be super valuable if you're willing
to document them!

As a sidenote, GitHub codespaces is a really nice dev experience, and that
puts you on an Ubuntu virtual machine. I think it's a limited roll-out, but
if you happen to have access to it, it might make your life easier!

**Comment by josephcscarpa** [comment]
I'll definitely try installing it on my local machine. My desktop has Linux dual-booted, but I need to change something in BIOS to access it. Will do.

**Comment by j6k4m8** [comment]
Hey @josephcscarpa! Just wanted to check in on this. I know it's been a busy few months :) Have you had a chance to play around with this? I'm also happy to pick this up if you haven't had time!

**Comment by j6k4m8** [comment]
hey @josephcscarpa — I had some time to play around this morning so I got this feature worked out, but if you're still interested in contributing to the project I'd be happy to collab on finding a new feature to work on :) 
(No pressure!)

**Comment by josephcscarpa** [comment]
@j6k4m8 Hey there. I got way more bogged down during the semester than I anticipated, but I'd be happy to look for a new feature. However, I still haven't even tried goosepaper to work with my Remarkable and Windows yet.
