### ISSUE TITLE
docker image 'p2r' is missing

### ISSUE THREAD

**Issue by kevingoh** [j6k4m8/goosepaper#4]
Hi,

It seems like p2r image is not in the dockerhub. This project is obsolete then?

Please advise.

Thanks.

**Comment by j6k4m8** [comment]
Hey @kevingoh, thanks for the report!

The `p2r` command is from [this repository](https://github.com/GjjvdBurg/paper2remarkable), as a short-term fix you can install directly from there (both python command `p2r` and the dockerized version will work here). I must have had a preexisting p2r image and never noticed that it wasn't on Docker Hub!

This project is definitely still alive (I use it every day!), so if you encounter any other issues, let me know and I will be happy to help get things working for you!

I'll work on pushing a longer-term fix to the repo, or at least better documentation about this :)

**Comment by j6k4m8** [comment]
@kevingoh I've added [an explanation to the readme](https://github.com/j6k4m8/goosepaper#p2r); realized I never mentioned it anywhere. Thanks again for the heads-up! Let me know if that solves your problem and we can close the issue :)

**Comment by kevingoh** [comment]
Hi @j6k4m8 ,

Yeah I am sorry that after I posted this issue I then found out p2r is actually paper2remarkable. Thanks for replying!
