### ISSUE TITLE
Global preferences

### ISSUE THREAD

**Issue by sedennial** [j6k4m8/goosepaper#44]
I think there should be a global preferences config file.

**Comment by j6k4m8** [comment]
Love this idea. Maybe something that extends the current goosepaper config, so that your global config looks like a goosepaper config, but a specified config file overrides those values? 

I propose that because I think it'd be convenient to have a single json spec that we have to parse...

**Comment by sedennial** [comment]
I like that idea too which is kinda what I was thinking. For example I'd like to have my default font size at 12, but on a couple of RSS feeds that are very verbose I'd like those to be at 10.

Plus I don't have a single big config file since I run all mine as separate cronjobs. Just a personal idiosyncrasy.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sedennial** [comment]
I'm working on this right now (mostly done) with a hard coded order of precedence as well as add ability for certain new options to be changed on a per story basis (like you can with font-size). The order of priority (from least to highest) is

1. $HOME/.goosepaper.json
2. $(CWD)/goosepaper.json (with CWD being the cwd of the shell at the time it called goosepaper, not the goosepaper directory. So this can be specified in either cron or windows task scheduler/.lnk file. Allows for you to have separate directory + config file (if you wanted) for each story job and contain every operational value in the config. No longer HAVE to specify ANY command line argument if you don't want to.
3. --config <configfile>.json
4. option-embedded-in-story-config
5. --<commandline-option>

**Comment by sedennial** [comment]
Oh, and I'm also adding a default 'goosepaper.json' which contains all (existing and new/pending) options with all options set to 'safe' mode where 'safe' means keep the functionality as it exists in 0.3.1 (0.3.7?) so as to not break existing workflow processes or expected behavior.

This means by default some of the new sanity checks options (when finalized) will be disabled.
