### ISSUE TITLE
Limit doesn't appear to be honored

### ISSUE THREAD

**Issue by sedennial** [j6k4m8/goosepaper#47]

**Comment by j6k4m8** [comment]
Can you elaborate? This is handled per-StoryProvider and they can (depending on internal behavior) do different things with this number.

**Comment by sedennial** [comment]
So for example I have the following config:
` "stories": [
        {
            "provider": "rss",
            "config": {
                "rss_path": "https://krebsonsecurity.com/feed/",
                "limit": 1,
                "skip": true
            }
        }
    ]
`

Yet instead of pulling only one item, I get the feed limit of 10.

With this one I get 42 pages of stories. Every time. :)
` "stories": [
        {
            "provider": "rss",
            "config": {
                "rss_path": "https://www.schneier.com/feed/atom/",
                "limit": 10
            }
        }
    ]
`

**Comment by sedennial** [comment]
Actually I *just* discovered that it's different behaviour depending on if I'm producing epub or pdf output. Epub give me 10. PDF seems to give me whatever the feed will serve up.

**Comment by j6k4m8** [comment]
Hm that's super interesting. I'll investigate!

**Comment by j6k4m8** [comment]
sho' 'nuf! we completely ignore the `limit` param in the rss story provider.

https://github.com/j6k4m8/goosepaper/blob/e26f6b1da7da2dc27d7aa8948bca73327e2659fd/goosepaper/rss.py#L22
