### ISSUE TITLE
Updating documentation

### ISSUE THREAD

**Issue by kwillno** [j6k4m8/goosepaper#51]
Hey, trying to get this to work again after having been gone for a while.  
Seems the docs in [docs](https://github.com/j6k4m8/goosepaper/tree/master/docs) is out of date for the new setup using `.json` config files. If i remember correctly the customization-setup given in docs is for the system that was in place some time ago.   
  
As I have recently poured over the files I could try to write something up to help others customize their goosepapers, i.e. what parameters you can set in the config file and what they do. Would also love a list of all the available storyproviders, and that shouldn't be too hard.  
Thoughts @j6k4m8 ?

**Comment by j6k4m8** [comment]
Hey @kwillno!! That's a great catch, indeed there are better ways now :) (Although that file is still a valid option.)

If you are interested, I'd love a docs revamp!! I can certainly help with available storyproviders; at least as of the moment, there are two places to look:
* The many files [in this repo](https://github.com/j6k4m8/goosepaper/tree/master/goosepaper); probably we should make all storyproviders live inside of a `goosepaper/storyproviders/` subdir, but that's for later :)
* [auxiliary-goose](https://github.com/j6k4m8/auxiliary-goose/), which is where I'm hoping to perhaps start centralizing storyproviders (at least, some) in the future

As a first pass,

* Ao3StoryProvider*
* HackerNewsStoryProvider*
* RedditStoryProvider
* RSSStoryProvider
* TwitterStoryProvider
* WeatherStoryProvider
* WikipediaStoryProvider

> \*: indicates `auxiliary-goose`

**Comment by kwillno** [comment]
Right!  
I started checking the storyproviders in this repo at least, but I will check the ones in [auxilliary-goose](https://github.com/j6k4m8/auxiliary-goose/) as well!  
  
If you (or anyone else i guess) have any preferences on how to present the different `.json` parameters I would love some input.

**Comment by kwillno** [comment]
Added #54 to amend this issue.  
#54 is only a first step. Will see what more I can contribute in terms of documentation.

**Comment by j6k4m8** [comment]
This is so awesome, thank you @kwillno!!
