### ISSUE TITLE
File/Folder sanity and case checks

### ISSUE THREAD

**Issue by sedennial** [j6k4m8/goosepaper#52]
Figured I'd start a discussion to make sure that before I write any more code  on this issue (and then revert it) I should make sure it's what you want to do. :)

Possible issues that can arise that need to (potentially) be resolved relating to document and folder naming.

1. Case identical duplicates (i.e. "Test Document" == "Test Document")
2. Case non-identical duplicate document (i.e. "Test document" == "test document")

There are FOUR possible modes of behavior I see available:

1. Enable case sensitivity for folders only
2. Enable case sensitivity for documents only
3. Enable case sensitivity for both (expected behavior for *nix/Mac)
4. Ignore case (expected behavior for Windows)

What I'm proposing is the below:

- '--ignorefoldercase'. This will treat folders 'My Goosepapers' and 'my goosepapers' as if they are the same folder.
- '--ignoredocumentcase'. Same as above, only for documents.
- '--windowsuploads'. A shortcut which would enable both case ignore options.
- '--unixuploads'. This would forcibly disable case comparison for both folders and documents. So 'My Folders/MyGoosepaper.pdf' and 'my folders/myGoosepaper.pdf' would be seen as two different folders and document names.

There is also the issue of how to proceed if we encounter identically named documents in the target upload folder or duplicate folders in the root (or eventually in child folders).

I propose these two behaviors for how to handle the errors:

1. In the event there is found a violation of the case policy, throw an error and generate an error report in the same location as the target document. So '--output MyGoosepaper.epub' would create an error report 'MyGoosepaper.ErrorReport' which would document the error.
2. Add '--uploadsanitycheck': This would NOT enable case ignore options, but it would perform a case insensitive check on the target upload folder (or root) for ANY duplicate document or folder names (not just the target document or folder name) and produce an error report detailing any duplicates found. But as I write this I'm almost wondering if this isn't something that should go into some type of non-goosepaper utility suite.

**Comment by j6k4m8** [comment]
Sorry for the late response here — I think you raise a lot of good points here!

### Case sensitivity 

My instinct is to mirror whatever reMarkable does on its tablets / apps, regardless of OS; my understanding is that the reMarkable is unix-style (is case-sensitive). I realize this is wonky for Windows users, but I think that the most sane thing to do is to emulate the behavior of the reMarkable app as closely as possible: If you could upload two files _from the app_ with the same name but for their case, then I think we should support that as well, without prompting the user.

Are there issues I'm not thinking of if we assert that we're unix-style in filename support? I don't want to break things for windows users unnecessarily (although... are you using windows? I don't have conclusive proof yet that Goosepaper even works on windows!)

### A utility for sanity checks

I really like this, and I totally agree that it probably merits its own standalone utility (which I expect Goosepaper will benefit from immensely!). Some potential additional features that might be able to live in that util suite are (off the top of my head),
* Lifecycle rules
  * Automatic deletion of older-than-X documents
  * Automatically move yesterday's goosepaper (etc) to an archive to await deletion after 30 days (so my homepage only ever has one goosepaper waiting?)
* Filename checks (like you mention!)
* Batch operations, file mirroring, or annotation exports!

---

Curious to hear your thoughts :)

**Comment by j6k4m8** [comment]
I think this is fixed in #48 — please let me know if you feel otherwise!
