### ISSUE TITLE
Metaweather went bye bye

### ISSUE THREAD

**Issue by floatingman** [j6k4m8/goosepaper#66]
https://i.imgur.com/9mT9KyR.png

Metaweather is either down or has ceased being a website.

**Comment by j6k4m8** [comment]
Thank you for reporting! I will look into this — hopefully just a service outage and they'll be back, but it probably wouldn't hurt for us to have a backup weather storyprovider anyway :)

**Comment by steima** [comment]
Perhaps we can remove the provider from the example for now?

**Comment by j6k4m8** [comment]
@steima — I have fixed this in #67, let me know if you run into any further issues :)
