### ISSUE TITLE
Read configuration from $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by Kernald** [j6k4m8/goosepaper#89]
When not using the Docker container, it would be quite nice having as few arguments as possible to pass. One easy one to have a default value for would be `-c`/`--config` - if not passed, having it defaulting to `$XDG_CONFIG_HOME/goosepaper.json` for example would be quite convenient.

**Comment by Kernald** [comment]
Aaaand I just found this:

https://github.com/j6k4m8/goosepaper/blob/970ca46839950c76bb2d7996da627f653574a499/goosepaper/multiparser.py#L100-L112

I guess the README needs updating:

https://github.com/j6k4m8/goosepaper/blob/970ca46839950c76bb2d7996da627f653574a499/README.md?plain=1#L104

**Comment by j6k4m8** [comment]
Ooh thanks for the heads-up about the readme! Will address shortly :) Is this closeable otherwise? i.e., do you feel happy with how configs work, or is there another option you'd like to see as a 4th option?

**Comment by Kernald** [comment]
I'm not closing it myself in case you want to keep this as a reminder to update the README, but definitely closable :-) Thanks!

**Comment by j6k4m8** [comment]
Fixed in the readme, thank you @Kernald!
