### ISSUE TITLE
Better User-Agent header for RSS feed requests

### ISSUE THREAD

**Issue by jpco** [j6k4m8/goosepaper#93]
The default User-Agent for the python requests library leads to 403 errors from certain blogs -- some googling indicates this might be a Cloudflare protection against (lazy) web scrapers.  Just setting something random like `headers={'User-Agent': 'goosepaper/0.0'}` for the `requests.get()` call at `rss.py:39` causes those blogs to work better.

**Comment by jpco** [comment]
Oh, for repro purposes, a good feed is https://civileats.com/feed/

**Comment by j6k4m8** [comment]
This is a great idea, thank you!

**Comment by j6k4m8** [comment]
Fixed in #94!
